export function formatKaiHelpText(): string {
  return [
    "Kai CLI",
    "",
    "Commands:",
    "  kai init",
    "  kai doctor",
    "  kai settings explain",
    "  kai tasks list",
    "  kai tasks read <task-id>",
    "  kai config show",
    "  kai skills list [--all]",
    "  kai agents list [--all]",
    "  kai memory add|list|search|explain|delete|archive|refresh|merge|promote|extract",
    "  kai context trace --session <id>",
    "  kai context replay --session <id>",
    "  kai context eval <fixture-path>",
    "  kai context tune <fixture-path>",
    "  kai context diff --session-a <id> --session-b <id>",
    "  kai run [--provider fixture --script <path>] [--session new|<id>] \"<task>\"",
    "  kai resume [--provider fixture --script <path>] <session-id> \"<task>\"",
    "  kai sessions [export|replay <session-id>]",
    "  kai plan open --session <session-id>",
    "  kai prompt --debug [--session <id>] [--json] [--show-items] [--max-input-tokens <n>] \"<task>\"",
    "  kai chat [<session-id>]",
    "",
    "Examples:",
    "  kai doctor",
    "  kai settings explain",
    "  kai tasks list",
    "  kai tasks read task_123",
    "  bun build --compile --outfile dist/kai src/cli/main.ts",
  ].join("\n");
}
